Fixs.
Signed-off-by: huaiyou <huaiyou.cyz@alibaba-inc.com>

diff --git a/build/plugins/configure_kubelet_shell_plugin.yaml b/build/plugins/configure_kubelet_shell_plugin.yaml
--- a/build/plugins/configure_kubelet_shell_plugin.yaml
+++ b/build/plugins/configure_kubelet_shell_plugin.yaml
@@ -15,19 +15,41 @@ spec:
       exit 1
     fi
     
-    # if not IPv6DualStack, just write one ip
-    if [ "${IPv6DualStack}" != "true" ];then
-      echo "KUBELET_EXTRA_ARGS=--node-ip=${HostIP}" > /etc/sysconfig/kubelet
-      exit 0
+    KUBELET_EXTRA_ARGS="KUBELET_EXTRA_ARGS=--node-ip=${HostIP}"
+
+    if [ "${IPv6DualStack}" == "true" ];then
+      family_of_ip_need_get=6
+      if [ "${HostIPFamily}" == "6" ];then
+        family_of_ip_need_get=4    
+      fi
+    
+      anotherIP=`trident get-default-route-ip --ip-family ${family_of_ip_need_get}`
+    
+      KUBELET_EXTRA_ARGS="${KUBELET_EXTRA_ARGS},${anotherIP}"
     fi
     
-    family_of_ip_need_get=6
-    if [ "${HostIPFamily}" == "6" ];then
-      family_of_ip_need_get=4    
+    if lspci | grep -i nvidia > /dev/null 2>&1;then
+      NVIDIA_GPU_NAME=$(nvidia-smi --query-gpu=gpu_name --format=csv,noheader --id=0 | sed -e 's/ /-/g')
+      if [[ "$NVIDIA_GPU_NAME" == "" ]]; then
+        echo 'nvidia GPU name query failed, please check using `nvidia-smi --query-gpu=gpu_name  --format=csv,noheader --id=0 `'
+        exit 1
+      fi
+    
+      NVIDIA_GPU_COUNT=$(nvidia-smi -L | wc -l)
+      if [[ "$NVIDIA_GPU_COUNT" == "0" ]]; then
+        echo 'nvidia GPU count query failed, please check using `nvidia-smi -L | wc -l`'
+        exit 1
+      fi
+
+      NVIDIA_GPU_MEMORY=$(nvidia-smi --id=0 --query-gpu=memory.total --format=csv,noheader | sed -e 's/ //g')
+      if [[ "$NVIDIA_GPU_MEMORY" == "" ]]; then
+        echo 'nvidia GPU memory resource query failed, please check using `nvidia-smi --id=0 --query-gpu=memory.total  --format=csv,noheader`'
+        exit 1
+      fi
+      KUBELET_EXTRA_ARGS="${KUBELET_EXTRA_ARGS} --node-labels=aliyun.accelerator/nvidia_name=$NVIDIA_GPU_NAME,aliyun.accelerator/nvidia_count=$NVIDIA_GPU_COUNT,aliyun.accelerator/nvidia_mem=$NVIDIA_GPU_MEMORY"
     fi
     
-    anotherIP=`trident get-default-route-ip --ip-family ${family_of_ip_need_get}`
-    echo "KUBELET_EXTRA_ARGS=--node-ip=${HostIP},${anotherIP}" > /etc/sysconfig/kubelet
+    echo $KUBELET_EXTRA_ARGS > /etc/sysconfig/kubelet
 
 ---
 apiVersion: sealer.aliyun.com/v1alpha1
@@ -47,16 +69,38 @@ spec:
       exit 1
     fi
     
-    # if not IPv6DualStack, just write one ip
-    if [ "${IPv6DualStack}" != "true" ];then
-      echo "KUBELET_EXTRA_ARGS=--node-ip=${HostIP}" > /etc/sysconfig/kubelet
-      exit 0
+    KUBELET_EXTRA_ARGS="KUBELET_EXTRA_ARGS=--node-ip=${HostIP}"
+
+    if [ "${IPv6DualStack}" == "true" ];then
+      family_of_ip_need_get=6
+      if [ "${HostIPFamily}" == "6" ];then
+        family_of_ip_need_get=4    
+      fi
+      
+      anotherIP=`trident get-default-route-ip --ip-family ${family_of_ip_need_get}`
+      
+      KUBELET_EXTRA_ARGS="${KUBELET_EXTRA_ARGS},${anotherIP}"
     fi
     
-    family_of_ip_need_get=6
-    if [ "${HostIPFamily}" == "6" ];then
-      family_of_ip_need_get=4    
+    if lspci | grep -i nvidia > /dev/null 2>&1;then
+      NVIDIA_GPU_NAME=$(nvidia-smi --query-gpu=gpu_name --format=csv,noheader --id=0 | sed -e 's/ /-/g')
+      if [[ "$NVIDIA_GPU_NAME" == "" ]]; then
+        echo 'nvidia GPU name query failed, please check using `nvidia-smi --query-gpu=gpu_name  --format=csv,noheader --id=0 `'
+        exit 1
+      fi
+    
+      NVIDIA_GPU_COUNT=$(nvidia-smi -L | wc -l)
+      if [[ "$NVIDIA_GPU_COUNT" == "0" ]]; then
+        echo 'nvidia GPU count query failed, please check using `nvidia-smi -L | wc -l`'
+        exit 1
+      fi
+
+      NVIDIA_GPU_MEMORY=$(nvidia-smi --id=0 --query-gpu=memory.total --format=csv,noheader | sed -e 's/ //g')
+      if [[ "$NVIDIA_GPU_MEMORY" == "" ]]; then
+        echo 'nvidia GPU memory resource query failed, please check using `nvidia-smi --id=0 --query-gpu=memory.total  --format=csv,noheader`'
+        exit 1
+      fi
+      KUBELET_EXTRA_ARGS="${KUBELET_EXTRA_ARGS} --node-labels=aliyun.accelerator/nvidia_name=$NVIDIA_GPU_NAME,aliyun.accelerator/nvidia_count=$NVIDIA_GPU_COUNT,aliyun.accelerator/nvidia_mem=$NVIDIA_GPU_MEMORY"
     fi
     
-    anotherIP=`trident get-default-route-ip --ip-family ${family_of_ip_need_get}`
-    echo "KUBELET_EXTRA_ARGS=--node-ip=${HostIP},${anotherIP}" > /etc/sysconfig/kubelet
+    echo $KUBELET_EXTRA_ARGS > /etc/sysconfig/kubelet
