fix helm values; fix docker clean volumes.
Signed-off-by: huaiyou <huaiyou.cyz@alibaba-inc.com>

diff --git a/build/plugins/configure_kubelet_shell_plugin.yaml b/build/plugins/configure_kubelet_shell_plugin.yaml
--- a/build/plugins/configure_kubelet_shell_plugin.yaml
+++ b/build/plugins/configure_kubelet_shell_plugin.yaml
@@ -10,6 +10,18 @@ spec:
     set -x
     sysctl -w net.ipv6.conf.all.forwarding=1
 
+    if [ "${IPv6DualStack}" = "true" ];then
+      configure_ipv6="net.ipv6.conf.all.disable_ipv6 = 0"
+      echo $configure_ipv6 > /etc/sysctl.d/ack-d-enable-ipv6.conf
+      if ! grep "${configure_ipv6}" /etc/sysctl.conf;then
+        echo "${configure_ipv6}" >> /etc/sysctl.conf
+      fi
+      if ! sysctl --system;then
+        echo "failed to run sysctl, please check"
+        exit 1
+      fi
+    fi
+
     if [ "${HostIP}" = "" ];then
       echo "Can't find HostIP in env, skip configure --node-ip"
     else
